-- liquibase formatted sql

-- changeset eorion:1 dbms:oracle
create table if not exists ENHANCEMENT_JOB_LOG
(
    ID_ VARCHAR2(64) not null PRIMARY KEY,
    JOB_ID_ VARCHAR2(64) not null,
    JOB_EXCEPTION_MSG_ VARCHAR2(4000),
    JOB_STATE_ NUMBER(10),
    TIMEOUT_ NUMBER(19),
    JOB_DEF_ID_ VARCHAR2(64),
    JOB_DEF_TYPE_ VARCHAR2(255),
    ACT_ID_ VARCHAR2(255),
    EXECUTION_ID_ VARCHAR2(64),
    ROOT_PROC_INST_ID_ VARCHAR2(64),
    PROCESS_INSTANCE_ID_ VARCHAR2(64),
    PROCESS_DEF_ID_ VARCHAR2(64),
    PROCESS_DEF_KEY_ VARCHAR2(255),
    DEPLOYMENT_ID_ VARCHAR2(64),
    TENANT_ID_ VARCHAR2(64),
    HOSTNAME_ VARCHAR2(255),
    EXECUTION_THREAD_NAME_ VARCHAR2(32),
    EXECUTION_START_TIMESTAMP_ timestamp not null,
    EXECUTION_COMPLETE_TIMESTAMP_ timestamp,
    EXECUTION_DURATION_ NUMBER(19),
    primary key (ID_)
)